apiVersion: apps/v1
kind: Deployment
metadata:
  name: psmdb-x509-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: psmdb-x509-tester
  template:
    metadata:
      labels:
        app.kubernetes.io/name: psmdb-x509-tester
    spec:
      containers:
      - name: tester
        image: egegunes/psmdb-x509-tester:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: ssl
          subPath: ca.crt
          mountPath: /etc/mongodb-ssl/ca.crt
        - name: x509
          mountPath: /etc/psmdb-x509-tester
      volumes:
      - name: ssl
        secret:
          secretName: cluster1-ssl
      - name: x509
        secret:
          secretName: cluster1-psmdb-egegunes
